----------------------------------
-- COMPANY - triElems           --
-- PROJECT NAME - GenericAPI    --
-- CHANNEL - FREELANCER.COM     --
-- CLIENT USER NAME - MALAGOPU  --
----------------------------------

CREATE TABLE "APIUSER"."TBL_WEBAPI_CONFIG" 
(	"SERVICE_ID" NUMBER(*,0), 
"REQUEST_TYPE" VARCHAR2(100 BYTE), 
"CONNECTIONSTR_ID" VARCHAR2(20 BYTE), 
"OBJ_TO_RETRIEVE_DATA" VARCHAR2(100 BYTE), 
"DB_TYPE" VARCHAR2(20 BYTE), 
"OBJ_TO_STORE_DATA" VARCHAR2(100 BYTE), 
"LATEST_BATCH_ID" VARCHAR2(20 BYTE)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;

CREATE OR REPLACE TRIGGER "APIUSER"."TBL_WEBAPI_CONFIG_TRG" 
BEFORE INSERT ON TBL_WEBAPI_CONFIG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SERVICE_ID IS NULL THEN
      SELECT TBL_WEBAPI_CONFIG_SEQ.NEXTVAL INTO :NEW.SERVICE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "APIUSER"."TBL_WEBAPI_CONFIG_TRG" ENABLE;

ALTER TABLE "APIUSER"."TBL_WEBAPI_CONFIG" MODIFY ("SERVICE_ID" NOT NULL ENABLE);

Create table TBL_LOAN_DETAILS(
    SEC_ID int,
    DATE_OF_LOAN DATE,
    ACCNT varchar2(50)
)

Create table TBL_LOAN_DETAILS_TEMP(
    SEC_ID int,
    DATE_OF_LOAN DATE,
    ACCNT varchar2(50),
    LOAN_QTY int
)

CREATE OR REPLACE PROCEDURE "APIUSER"."SPSELECTLOANDETAIL" 
(
    SecurityId IN INT,
    RC OUT SYS_REFCURSOR
)
AS 
BEGIN
  OPEN RC FOR SELECT * FROM TBL_LOAN_DETAILS
  WHERE SEC_ID = SecurityId;
END SPSELECTLOANDETAIL;

CREATE OR REPLACE PROCEDURE "APIUSER"."SPSELECTCONFIGURATION" 
(
    ServiceId IN INT,
    RC OUT SYS_REFCURSOR
)
AS 
BEGIN
  OPEN RC FOR SELECT * FROM TBL_WEBAPI_CONFIG
  WHERE SERVICE_ID = ServiceId;
END SPSELECTCONFIGURATION;

CREATE OR REPLACE PROCEDURE SPINSERTTEMPDATA
(
    DateOfLoan IN Date,
    AccountType IN varchar2,
    LoanQty IN INT
)
AS 
BEGIN
  INSERT INTO TBL_LOAN_DETAILS_TEMP (DATE_OF_LOAN,ACCNT,LOAN_QTY) VALUES (DateOfLoan,AccountType,LoanQty);
END SPINSERTTEMPDATA;

-- DATA --
INSERT INTO TBL_LOAN_DETAILS (KEY,SEC_ID,DATE_OF_LOAN,ACCNT) VALUES (1,1,TO_DATE('2017/07/23','yyyy/mm/dd'),'Development');
INSERT INTO TBL_LOAN_DETAILS (KEY,SEC_ID,DATE_OF_LOAN,ACCNT) VALUES (2,2,TO_DATE('2017/04/18','yyyy/mm/dd'),'Normal');
INSERT INTO TBL_LOAN_DETAILS (KEY,SEC_ID,DATE_OF_LOAN,ACCNT) VALUES (3,3,TO_DATE('2017/04/13','yyyy/mm/dd'),'Production');
INSERT INTO TBL_LOAN_DETAILS (KEY,SEC_ID,DATE_OF_LOAN,ACCNT) VALUES (4,3,TO_DATE('2017/04/10','yyyy/mm/dd'),'Something');

INSERT INTO TBL_WEBAPI_CONFIG (REQUEST_TYPE,CONNECTIONSTR_ID,OBJ_TO_RETRIEVE_DATA,DB_TYPE,OBJ_TO_STORE_DATA,LATEST_BATCH_ID) VALUES ('loananalaytics','ORACLE','SPSELECTLOANDETAIL','ORACLE','SPINSERTLOANDETAILS','20');
INSERT INTO TBL_WEBAPI_CONFIG (REQUEST_TYPE,CONNECTIONSTR_ID,OBJ_TO_RETRIEVE_DATA,DB_TYPE,OBJ_TO_STORE_DATA,LATEST_BATCH_ID) VALUES ('loananalaytics','SQLSERVER','SPSELECTLOANDETAIL','SQLSERVER','SPINSERTLOANDETAILS','30');
INSERT INTO TBL_WEBAPI_CONFIG (REQUEST_TYPE,CONNECTIONSTR_ID,OBJ_TO_RETRIEVE_DATA,DB_TYPE,OBJ_TO_STORE_DATA,LATEST_BATCH_ID) VALUES ('loananalaytics','ORACLE,SQLSERVER','SPSELECTLOANDETAIL','ORACLE,SQLSERVER','SPINSERTLOANDETAILS','40');